#!/bin/bash

a=$(wmctrl -root -children -l | grep -o "$HOSTNAME.*" | sed "s/$HOSTNAME //g" | awk -F "— " '{ print $NF }' | awk -F "- " '{ print $NF }' | sed '/Plasma/d' | sed 's/^Slack.*éléments/slack/g' | sed 's/^Slack.*opensource/slack/g' | sed 's/^Latte.*Dock/lattedock/g' | sed 's/^Google.*Chrome/google-chrome/g' | sed 's/^Gestionnaire.*Muon/muon/g' | tr '[:upper:]' '[:lower:]' | sed '/^/G')
/etc/alternatives/tts "$a" 
