#!/bin/bash

if [ "$1" == "shutdown" ]
then
/etc/alternatives/tts "Le PC s'éteint"
qdbus org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout 0 2 3
fi

if [ "$1" == "reboot" ]
then
/etc/alternatives/tts "Le PC reboot"
qdbus org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout 0 1 3
fi

