1 : afficher bureau : Ctrl+F12
1 : basculer cinquième : Meta+5
1 : basculer deuxième : Meta+2
1 : basculer deuxième : Meta+2
1 : basculer premier : Meta+1
1 : basculer quatrième : Meta+4
1 : basculer sixième : Meta+6
1 : basculer troisième : Meta+3
4 : configuration audio : /usr/bin/pavucontrol-qt
4 : configuration ordinateur : /usr/bin/drakconf
4 : configuration système : /usr/bin/systemsettings5
4 : démarrer éditer : /usr/bin/kate
4 : démarrer explorateur : /usr/bin/dolphin
4 : démarrer lecteur flux : /usr/bin/akregator
4 : démarrer photo : /usr/bin/gwenview
1 : deuxième bureau : Ctrl+F2
1 : fenêtre bas : Meta+Alt+Down
1 : fenêtre haut : Meta+Alt+Up
1 : fenêtre droite : Meta+Alt+Right
1 : fenêtre gauche : Meta+Alt+Left
3 : flux précédent : "p"
3 : flux suivant : "n"
1 : maximiser fenêtre : Meta+PgUp
1 : menu application : Alt+F1
1 : menu fenêtre : Alt+F3
1 : nouveau dossier : F10
1 : plein écran : Meta+Ctrl+F11
1 : premier bureau : Ctrl+F1
1 : présenter fenêtre : Ctrl+F10
1 : processus : Ctrl+Esc
1 : quatrième bureau : Ctrl+F4
1 : remonter dossier : Alt+Up
1 : troisième bureau : Ctrl+F3
1 : verrouiller écran : Ctrl+Alt+L
